# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=250)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('skills', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('highschool_marks', models.IntegerField()),
                ('intermediate_marks', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
