# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='father_name',
        ),
    ]
