# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0002_login_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_form',
            name='user',
        ),
        migrations.DeleteModel(
            name='Login_form',
        ),
    ]
