# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0006_remove_userprofile_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mother_name',
        ),
    ]
