# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0007_remove_userprofile_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='BTechMarks',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 33, 21, 541216, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ExperienceDesc',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 33, 31, 919176, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='HighSchool',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 33, 38, 710924, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='HignSchool_Marks',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 33, 48, 123504, tzinfo=utc), max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='IntermediateMarks',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 33, 55, 791661, tzinfo=utc), max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='IntermediateSchool',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 5, 582115, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achieveDesc',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 10, 625787, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 15, 718523, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interestDesc',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 20, 983337, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 27, 312205, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phno',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 33, 979613, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projectDesc',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 41, 703203, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projectTitle',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 34, 49, 187577, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skillsSet',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 35, 5, 496201, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.CharField(default=datetime.datetime(2017, 4, 15, 11, 35, 10, 879287, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
