# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0008_auto_20170415_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
