# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0011_auto_20170415_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ExperienceDesc',
            new_name='Achieve_Desc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='BTechMarks',
            new_name='BTech_Marks',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='achieveDesc',
            new_name='Experience_Desc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='HignSchool_Marks',
            new_name='HighSchool_Marks',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='IntermediateMarks',
            new_name='Intermediate_Marks',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='IntermediateSchool',
            new_name='Intermediate_School',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='interestDesc',
            new_name='Project_Desc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='projectTitle',
            new_name='Project_Title',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='projectDesc',
            new_name='interest_Desc',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='skillsSet',
            new_name='skills_Set',
        ),
    ]
