# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0012_auto_20170415_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Self_Description',
            field=models.CharField(default=datetime.datetime(2017, 4, 17, 16, 54, 17, 293580, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
