# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0013_userprofile_self_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(default='images/None/no-img.jpg', upload_to='images/'),
        ),
    ]
