# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opm_app', '0016_auto_20170418_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
